### ISSUE TITLE
script throwing an error when typing 'a' to download the course

### ISSUE THREAD

**Issue by jairoguerra89** [sahilsehwag/pluralsight-downloader-chrome-extension#2]
Hey guys

I was trying to download a course when playing a video from the course but I noticed this in the console

![image](https://user-images.githubusercontent.com/36425695/98278125-ca37b480-1f5d-11eb-9f16-57ed61d7c1b9.png)

name.replace is not a function the last place it fails following the trace is here 

const nameToFilename = (name) => name.replace(/[\/:?><]/g, " ").trim();

**Comment by sahilsehwag** [comment]
Hey, Thanks for pointing out this bug, I am looking into it

**Comment by sahilsehwag** [comment]
Hi, I looked into it, I think you are using the old version of extension, because in the new version, 'a' have been replaced with 'c' to download the entire course, and the code in the stacktrace belongs to one of the previous versions, can you try with the latest version and let us know?
Regarding that 'c' key to download the course instead of 'a', that's my bad I forgot to update the key in main section of README, that's available in CHANGELOG section.

**Comment by jairoguerra89** [comment]
Alright , I downloaded the master version , that is working fine

**Comment by sahilsehwag** [comment]
I am closing the issue, if similar issue arises in the master version, you can reopen the issue and let us know.
