### ISSUE TITLE
Key Binding Not working

### ISSUE THREAD

**Issue by afeso** [sahilsehwag/pluralsight-downloader-chrome-extension#27]
Hello,

I've Successfully installed the app in Chrome and activated it, but the icon remains grey. 

I've tried the key bindings on various videos, but nothing seems to happen. 

Is there any additional setup that's needed?

**Comment by gcollis1** [comment]
Also not working for me

**Comment by sahilsehwag** [comment]
Hey @gcollis1 , we will removing support for the keybindings in near future, you can use the new extension popup to download the courses

**Comment by sahilsehwag** [comment]
@afeso @gcollis1 
Hey can you share the steps you used to install the extension?

**Comment by gcollis1** [comment]
download zip
unzip

Alternatively, open this page by clicking on the Extensions menu button and selecting Manage Extensions at the bottom of the menu.
Enable Developer Mode by clicking the toggle switch next to Developer mode.
Click the Load unpacked button and select the extension directory
nothing happens when i press e whilst watching a video

**Comment by sahilsehwag** [comment]
@gcollis1 
I can download the content with the keypress, Its working fine

We have added an extension UI to do the same actions, Have you tried downloading the video using buttons that are shown when we click on extension icon in chrome bar? Can you try that and let me know?
The reason I am asking this is because in the near future I will remove the shortcuts, and everything will be done through extension popup.

Alternatively you can check if the extension is working or not by
1. Right click on page where video player is open 
2.  Select the `Inspect` option
3. A window will open, Go to the `Console` tab
4. There will be a dropdown shown with a select value of `Top`, Can you click on that select the option with the name `PluralsightCourseDownloaderExtension`
5. Now try the shortcuts like `e` to enable and `c` to download the course
6. Can you take the screenshot of whatever that's being printed there and share the screenshots here

**Comment by shakaibakhtar** [comment]
![image](https://user-images.githubusercontent.com/53038317/125215873-0635cd00-e2d6-11eb-94e2-c1bfccc954e6.png)

**Comment by sahilsehwag** [comment]
@shakaibakhtar 
Did you stopped the downloading yourself, or did it happened on its own?

If it happened on its own, Can you tell how did you started the downloading (using keyboard shortcut(which keyboard shortcut) or using extension's UI?

**Comment by shakaibakhtar** [comment]
It stopped on its own. on page load I pressed e which and then pressed c, then the text in the Screenshot attached in above comment was printed and download was'nt started.

**Comment by vegazbabz** [comment]
Seems like it is blocked?

GET https://pluralsight.hb.omtrdc.net/?s:sc:rsid=pluralsight.united.dev&s:sc:tracki....... net::ERR_BLOCKED_BY_CLIENT

**Comment by amitkumar2283** [comment]
I am facing a similar issue. 

1. What I have down till now:

The plugin is installed and looks like this:
![image](https://user-images.githubusercontent.com/17488415/137070622-0f86434a-0a46-4973-b912-430d66cd86e6.png)

Clicking on the plugin does not open any UI (Not sure if it is supposed to)
![image](https://user-images.githubusercontent.com/17488415/137070704-d038520a-1ef7-4fd1-8441-49ca78b23ab2.png)

2. What is the behavior that I am experiencing:
When I play a pluralsight video, pressing 'e' does not provide any feedback, hence I am not sure if it is working or not.
Pressing 'c' just enables/disables captions and does nothing else.

3. More Details:
here is the console grab:
![image](https://user-images.githubusercontent.com/17488415/137070970-c209d2dc-a79f-4d3c-a648-a8435e30a89a.png)

**Comment by amitkumar2283** [comment]
Thank you for the blazingly fast response. 
I have installed 0.3 alpha; Is this not the latest?

**Comment by DenisMtfl** [comment]
Its not working anymore.

**Comment by ogeeDeveloper** [comment]
does not work when in press c it enables and disables subtitles

**Comment by chrispaivacwb** [comment]
> I am facing a similar issue.
> 
> 1. What I have down till now:
> 
> The plugin is installed and looks like this: ![image](https://user-images.githubusercontent.com/17488415/137070622-0f86434a-0a46-4973-b912-430d66cd86e6.png)
> 
> Clicking on the plugin does not open any UI (Not sure if it is supposed to) ![image](https://user-images.githubusercontent.com/17488415/137070704-d038520a-1ef7-4fd1-8441-49ca78b23ab2.png)
> 
> 2. What is the behavior that I am experiencing:
>    When I play a pluralsight video, pressing 'e' does not provide any feedback, hence I am not sure if it is working or not.
>    Pressing 'c' just enables/disables captions and does nothing else.
> 3. More Details:
>    here is the console grab:
>    ![image](https://user-images.githubusercontent.com/17488415/137070970-c209d2dc-a79f-4d3c-a648-a8435e30a89a.png)

Same issue here, not working.

**Comment by chrispaivacwb** [comment]
its not working for me.

![pluralsight_error](https://user-images.githubusercontent.com/52515054/148666709-5cd8ea97-5915-41be-a317-126298723528.png)

**Comment by sahilsehwag** [comment]
Hey keybindings are not supported in latest versions, in latest version we have UI/popup to do the same actions.
